drop table CLASS_NUM if exists;

CREATE TABLE CLASS_NUM(
SCHOOL_CD CHAR(3) NOT NULL,
CLASS_NUM VARCHAR(5) NOT NULL
);

ALTER TABLE CLASS_NUM
ADD PRIMARY KEY (SCHOOL_CD,CLASS_NUM);

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM) VALUES
('tes', '101'),
('tes', '102'),
('tes', '201'),
('tes', '202');