drop table TEST if exists;

CREATE TABLE TEST(
STUDENT_NO VARCHAR(10) NOT NULL,
SUBJECT_CD CHAR(3) NOT NULL,
SCHOOL_CD CHAR(10) NOT NULL,
NO INT NOT NULL,
POINT INT DEFAULT NULL,
CLASS_NUM VARCHAR(5) DEFAULT NULL
);

ALTER TABLE TEST
ADD PRIMARY KEY (STUDENT_NO,SUBJECT_CD,SCHOOL_CD,NO);